INSERT INTO produto (nome, valor_porcao) VALUES
('Pão Francês', 2),
('Pão de Leite', 2)
('Pão sem Glúten', 2),
('Pão de Forma', ),
('Croissant de Manteiga' ,3),
('Pão de queijo' ,1),
('Mussarela',5),
('Presunto',5),
('Baguete', 10),
('Torta', ),
('Brownie', ),
('Empada', ),
('Café Expresso', 2),
('Suco Natural', ),
('Chás', ),
('Dunuts', ),
('Requeijão', ),